export enum AdminPermissionEnum {
	GET_USERS = 'GET_USERS',
	CREATE_USER = 'CREATE_USER',
	UPDATE_USER = 'UPDATE_USER',
	DELETE_USER = 'DELETE_USER',

	GET_PROJECTS = 'GET_PROJECTS',
	CREATE_PROJECT = 'CREATE_PROJECT',
	UPDATE_PROJECT = 'UPDATE_PROJECT',
	DELETE_PROJECT = 'DELETE_PROJECT',

	GET_BOARDS = 'GET_BOARDS',
	CREATE_BOARD = 'CREATE_BOARD',
	UPDATE_BOARD = 'UPDATE_BOARD',
	DELETE_BOARD = 'DELETE_BOARD',

	GET_LISTS = 'GET_LISTS',
	CREATE_LIST = 'CREATE_LIST',
	UPDATE_LIST = 'UPDATE_LIST',
	DELETE_LIST = 'DELETE_LIST',

	GET_CARDS = 'GET_CARDS',
	CREATE_CARD = 'CREATE_CARD',
	UPDATE_CARD = 'UPDATE_CARD',
	DELETE_CARD = 'DELETE_CARD',
}
