export enum BoardPermissionEnum {
	GET_BOARD = 'GET_BOARD',
	CREATE_BOARD = 'CREATE_BOARD',
	UPDATE_BOARD = 'UPDATE_BOARD',
	DELETE_BOARD = 'DELETE_BOARD',

	INVITE_MEMBER = 'INVITE_MEMBER',
	REMOVE_MEMBER = 'REMOVE_MEMBER',
	UPDATE_MEMBER_ROLE = 'UPDATE_MEMBER_ROLE',
}
