export enum CardPermissionEnum {
	GET_CARD = 'GET_CARD',
	CREATE_CARD = 'CREATE_CARD',
	UPDATE_CARD = 'UPDATE_CARD',
	DELETE_CARD = 'DELETE_CARD',

	MOVE_CARD = 'MOVE_CARD',
	ASSIGN_MEMBER = 'ASSIGN_MEMBER',
	UNASSIGN_MEMBER = 'UNASSIGN_MEMBER',
}
