export enum ListPermissionEnum {
	GET_LIST = 'GET_LIST',
	CREATE_LIST = 'CREATE_LIST',
	UPDATE_LIST = 'UPDATE_LIST',
	DELETE_LIST = 'DELETE_LIST',

	MOVE_LIST = 'MOVE_LIST',
	INVITE_MEMBER = 'INVITE_MEMBER',
	REMOVE_MEMBER = 'REMOVE_MEMBER',
	UPDATE_MEMBER_ROLE = 'UPDATE_MEMBER_ROLE',
}
