export enum ListPermissionEnum {
	GET_LIST = 'GET_LIST',
	CREATE_LIST = 'CREATE_LIST',
	UPDATE_LIST = 'UPDATE_LIST',
	ARCHIVE_LIST = 'ARCHIVE_LIST',
	UNARCHIVE_LIST = 'UNARCHIVE_LIST',
	DELETE_LIST = 'DELETE_LIST',

	MOVE_LIST = 'MOVE_LIST',
}
