export enum ProjectPermissionEnum {
	GET_PROJECT = 'GET_PROJECT',
	CREATE_PROJECT = 'CREATE_PROJECT',
	UPDATE_PROJECT = 'UPDATE_PROJECT',
	ARCHIVE_PROJECT = 'ARCHIVE_PROJECT',
	UNARCHIVE_PROJECT = 'UNARCHIVE_PROJECT',
	DELETE_PROJECT = 'DELETE_PROJECT',

	INVITE_MEMBER = 'INVITE_MEMBER',
	REMOVE_MEMBER = 'REMOVE_MEMBER',
	UPDATE_MEMBER_ROLE = 'UPDATE_MEMBER_ROLE',
}
